name: unpubd
version: 0.0.8
publish_to: none
homepage: https://github.com/petrleocompel/unpubd
description: Self hosted Dart Pub Server. Host your enterprise Dart packages internally using the same web interface and tools as pub.dev.
repository: https://github.com/petrleocompel/unpubd
environment:
  sdk: ">=2.14.1 <3.0.0"
dependencies:
  args: ^2.0.0
  dcli: ^1.14.0
  dcli_core: ^1.36.2
  docker2: ^2.1.2
  meta: ^1.7.0
  mongo_dart: ^0.7.4
  path: ^1.8.0
  settings_yaml: ^4.0.1
  unpub:
    git: 
      url: https://github.com/petrleocompel/unpub.git
      path: unpub
  yaml: ^3.1.0
dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.5
executables:
  unpubd:
  unpub:
